from typing import List

PATHS: List[str] = [

]

ASSEMBLIES: List[str] = [
    # | System
    # 'System',
    # 'System.Collections',
    # 'System.ComponentModel',
    # 'System.Configuration',
    # 'System.Data',
    # 'System.Data.Common',
    # 'System.Drawing',
    # 'System.IO',
    # 'System.Net',
    # 'System.Reflection',
    # 'System.Runtime',
    # 'System.Security',
    # 'System.Threading',
    # 'System.Web',
    # 'System.Windows',
    # 'System.Windows.Forms',
    # 'System.Xml',
    
    'System',
    'System.Activities',
    'System.Activities.Core.Presentation',
    'System.Activities.DurableInstancing',
    'System.Activities.Presentation',
    'System.AddIn',
    'System.AddIn.Contract',
    'System.AppContext',
    'System.Collections',
    'System.Collections.Concurrent',
    'System.Collections.NonGeneric',
    'System.Collections.Specialized',
    'System.ComponentModel',
    'System.ComponentModel.Annotations',
    'System.ComponentModel.Composition',
    'System.ComponentModel.DataAnnotations',
    'System.ComponentModel.EventBasedAsync',
    'System.ComponentModel.Primitives',
    'System.ComponentModel.TypeConverter',
    'System.Configuration',
    'System.Configuration.Install',
    'System.Console',
    'System.Core',
    'System.Data',
    'System.Data.Common',
    'System.Data.DataSetExtensions',
    'System.Data.Entity',
    'System.Data.Entity.Design',
    'System.Data.Linq',
    'System.Data.OracleClient',
    'System.Data.Services',
    'System.Data.Services.Client',
    'System.Data.Services.Design',
    'System.Data.SqlXml',
    'System.Deployment',
    'System.Design',
    'System.Device',
    'System.Diagnostics.Contracts',
    'System.Diagnostics.Debug',
    'System.Diagnostics.FileVersionInfo',
    'System.Diagnostics.Process',
    'System.Diagnostics.StackTrace',
    'System.Diagnostics.TextWriterTraceListener',
    'System.Diagnostics.Tools',
    'System.Diagnostics.TraceSource',
    'System.Diagnostics.Tracing',
    'System.DirectoryServices',
    'System.DirectoryServices.AccountManagement',
    'System.DirectoryServices.Protocols',
    'System.Drawing',
    'System.Drawing.Design',
    'System.Drawing.Primitives',
    'System.Dynamic',
    'System.Dynamic.Runtime',
    'System.Globalization',
    'System.Globalization.Calendars',
    'System.Globalization.Extensions',
    'System.IO',
    'System.IO.Compression',
    'System.IO.Compression.FileSystem',
    'System.IO.Compression.ZipFile',
    'System.IO.FileSystem',
    'System.IO.FileSystem.DriveInfo',
    'System.IO.FileSystem.Primitives',
    'System.IO.FileSystem.Watcher',
    'System.IO.IsolatedStorage',
    'System.IO.Log',
    'System.IO.MemoryMappedFiles',
    'System.IO.Pipes',
    'System.IO.UnmanagedMemoryStream',
    'System.IdentityModel',
    'System.IdentityModel.Selectors',
    'System.IdentityModel.Services',
    'System.Linq',
    'System.Linq.Expressions',
    'System.Linq.Parallel',
    'System.Linq.Queryable',
    'System.Management',
    'System.Management.Instrumentation',
    'System.Messaging',
    'System.Net',
    'System.Net.Http',
    'System.Net.Http.Rtc',
    'System.Net.Http.WebRequest',
    'System.Net.NameResolution',
    'System.Net.NetworkInformation',
    'System.Net.Ping',
    'System.Net.Primitives',
    'System.Net.Requests',
    'System.Net.Security',
    'System.Net.Sockets',
    'System.Net.WebHeaderCollection',
    'System.Net.WebSockets',
    'System.Net.WebSockets.Client',
    'System.Numerics',
    'System.Numerics.Vectors',
    'System.ObjectModel',
    'System.Reflection',
    'System.Reflection.Emit',
    'System.Reflection.Emit.ILGeneration',
    'System.Reflection.Emit.Lightweight',
    'System.Reflection.Extensions',
    'System.Reflection.Primitives',
    'System.Reflection.context',
    'System.Resources.Reader',
    'System.Resources.ResourceManager',
    'System.Resources.Writer',
    'System.Runtime',
    'System.Runtime.Caching',
    'System.Runtime.CompilerServices.VisualC',
    'System.Runtime.DurableInstancing',
    'System.Runtime.Extensions',
    'System.Runtime.Handles',
    'System.Runtime.InteropServices',
    'System.Runtime.InteropServices.RuntimeInformation',
    'System.Runtime.InteropServices.WindowsRuntime',
    'System.Runtime.Numerics',
    'System.Runtime.Remoting',
    'System.Runtime.Serialization',
    'System.Runtime.Serialization.Formatters',
    'System.Runtime.Serialization.Formatters.Soap',
    'System.Runtime.Serialization.Json',
    'System.Runtime.Serialization.Primitives',
    'System.Runtime.Serialization.Xml',
    'System.Runtime.WindowsRuntime',
    'System.Runtime.WindowsRuntime.UI.Xaml',
    'System.Security',
    'System.Security.Claims',
    'System.Security.Cryptography.Algorithms',
    'System.Security.Cryptography.Csp',
    'System.Security.Cryptography.Encoding',
    'System.Security.Cryptography.Primitives',
    'System.Security.Cryptography.X509Certificates',
    'System.Security.Principal',
    'System.Security.SecureString',
    'System.ServiceModel',
    'System.ServiceModel.Activation',
    'System.ServiceModel.Activities',
    'System.ServiceModel.Channels',
    'System.ServiceModel.Discovery',
    'System.ServiceModel.Duplex',
    'System.ServiceModel.Http',
    'System.ServiceModel.Internals',
    'System.ServiceModel.NetTcp',
    'System.ServiceModel.Primitives',
    'System.ServiceModel.Routing',
    'System.ServiceModel.Security',
    'System.ServiceModel.ServiceMoniker40',
    'System.ServiceModel.WasHosting',
    'System.ServiceModel.Web',
    'System.ServiceProcess',
    'System.Text.Encoding',
    'System.Text.Encoding.Extensions',
    'System.Text.RegularExpressions',
    'System.Threading',
    'System.Threading.Overlapped',
    'System.Threading.Tasks',
    'System.Threading.Tasks.Parallel',
    'System.Threading.Thread',
    'System.Threading.ThreadPool',
    'System.Threading.Timer',
    'System.Transactions',
    'System.ValueTuple',
    'System.Web',
    'System.Web.Abstractions',
    'System.Web.ApplicationServices',
    'System.Web.DataVisualization',
    'System.Web.DataVisualization.Design',
    'System.Web.DynamicData',
    'System.Web.DynamicData.Design',
    'System.Web.Entity',
    'System.Web.Entity.Design',
    'System.Web.Extensions',
    'System.Web.Extensions.Design',
    'System.Web.Mobile',
    'System.Web.RegularExpressions',
    'System.Web.Routing',
    'System.Web.Services',
    'System.Windows',
    'System.Windows.Forms',
    'System.Windows.Forms.DataVisualization',
    'System.Windows.Forms.DataVisualization.Design',
    'System.Workflow.Activities',
    'System.Workflow.ComponentModel',
    'System.Workflow.Runtime',
    'System.WorkflowServices',
    'System.Xaml',
    'System.Xaml.Hosting',
    'System.Xml',
    'System.Xml.Linq',
    'System.Xml.ReaderWriter',
    'System.Xml.Serialization',
    'System.Xml.XDocument',
    'System.Xml.XPath',
    'System.Xml.XPath.XDocument',
    'System.Xml.XmlDocument',
    'System.Xml.XmlSerializer',
]

BUILT_INS: List[str] = [
    'clr',
    'mscorlib',
]
