__all__ = [
    'GeneratedCodeAttribute',
    'IndentedTextWriter',
]


# TODO

# ---------- CLASSES ---------- #

class GeneratedCodeAttribute:
    """Identifies code generated by a tool. This class cannot be inherited."""


class IndentedTextWriter:
    """Provides a text writer that can indent new lines by a tab string token."""
